import Head from 'next/head';
import { useSubscription } from '@/hooks';
import { useEffect } from 'react';
import HomeList from '@/components/MainPage/HomeList';
import HeadTitle from '@/components/GlobalComponents/HeadTitle/HeadTitle';

// 1. 전체리스트 및 상세리스트 불러오기
// 2. 전체리스트 + 상세리스트 합치기
// 3. 카테고리별 분류 - 지역
// 4. 카테고리별 분류 -

const MainPage = () => {
  const { homeListHandler, homeList } = useSubscription();

  console.log(homeList);

  useEffect(() => {
    homeListHandler();
  }, []);

  return (
    <>
      <Head>
        <HeadTitle title="" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>오늘 청약</div>
        <div>청약 임박</div>
        <div>무순위</div>
      </div>

      <div>
        <button>오늘 청약</button>
        <button>청약 임박</button>
        <button>무순위</button>
      </div>
      <div>
        {/* TODO: props로 넘겨주지 않고 각 컴포넌트에서 실행하기? */}
        {homeList.map((item: any) => (
          <HomeList key={item.PBLANC_NO} home={item} />
        ))}
      </div>
    </>
  );
};

export default MainPage;
